### ISSUE TITLE
Permission Bitfiled

### ISSUE THREAD

**Issue by VampireTechnologyLord** [clqu/discord.js-v13-slash-bot#2]
When trying to start the bot, it says 
```bat
PS D:\Dateien\Dev\LXABot> node index.js
D:\Dateien\Dev\LXABot\node_modules\discord.js\src\util\BitField.js:152
    throw new RangeError('BITFIELD_INVALID', bit);
    ^

RangeError [BITFIELD_INVALID]: Invalid bitfield flag or number: undefined.
    at Function.resolve (D:\Dateien\Dev\LXABot\node_modules\discord.js\src\util\BitField.js:152:11)
    at D:\Dateien\Dev\LXABot\node_modules\discord.js\src\util\BitField.js:147:54
    at Array.map (<anonymous>)
    at Function.resolve (D:\Dateien\Dev\LXABot\node_modules\discord.js\src\util\BitField.js:147:40)
    at Client._validateOptions (D:\Dateien\Dev\LXABot\node_modules\discord.js\src\client\Client.js:546:33)
    at new Client (D:\Dateien\Dev\LXABot\node_modules\discord.js\src\client\Client.js:73:10)
    at Object.<anonymous> (D:\Dateien\Dev\LXABot\index.js:7:16)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32) {
  [Symbol(code)]: 'BITFIELD_INVALID'
}
```
I'd think this is because the permission integer wasnt set because there is no space for that. Please add one.

**Comment by VampireTechnologyLord** [comment]
Sorry, i havent created the authentication yet

**Comment by VampireTechnologyLord** [comment]
Doing just that sadly didnt fix the issue

**Comment by clqu** [comment]
Check this; https://github.com/clqu/discord.js-v13-slash-bot/commit/e4e2bcd1635f29990367e4bbda40007f27cdd56b
